var searchData=
[
  ['data_0',['data',['../classsul_1_1dynamic__bitset.html#adfe46260b7caff45a27990b37b771a98',1,'sul::dynamic_bitset::data() noexcept'],['../classsul_1_1dynamic__bitset.html#ad67d6b126707fecda32e4f363dc08394',1,'sul::dynamic_bitset::data() const noexcept']]],
  ['default_20values_1',['Default values',['../index.html#autotoc_md8',1,'']]],
  ['dependency_2',['Optional dependency',['../index.html#autotoc_md3',1,'']]],
  ['descriptions_3',['Descriptions',['../index.html#autotoc_md7',1,'']]],
  ['documentation_4',['Build tests, example, and documentation',['../index.html#autotoc_md9',1,'']]],
  ['dynamic_5fbitset_5',['dynamic_bitset',['../classsul_1_1dynamic__bitset.html',1,'sul::dynamic_bitset&lt; Block, Allocator &gt;'],['../classsul_1_1dynamic__bitset.html#a918cd9596247438bc2726456ef16e704',1,'sul::dynamic_bitset::dynamic_bitset(const dynamic_bitset&lt; Block, Allocator &gt; &amp;other)=default'],['../classsul_1_1dynamic__bitset.html#a7619a5398b7ca8d5e159b85312b74e29',1,'sul::dynamic_bitset::dynamic_bitset(dynamic_bitset&lt; Block, Allocator &gt; &amp;&amp;other) noexcept=default'],['../classsul_1_1dynamic__bitset.html#afb793e3c88667e7aa9223990ecc0c62b',1,'sul::dynamic_bitset::dynamic_bitset(const allocator_type &amp;allocator=allocator_type())'],['../classsul_1_1dynamic__bitset.html#aa4476cdab02d543ec8535bc2889c18b5',1,'sul::dynamic_bitset::dynamic_bitset(size_type nbits, unsigned long long init_val=0, const allocator_type &amp;allocator=allocator_type())'],['../classsul_1_1dynamic__bitset.html#a9e9c5ca51c73fce6cbce74e7c3ecdd97',1,'sul::dynamic_bitset::dynamic_bitset(std::initializer_list&lt; block_type &gt; init_vals, const allocator_type &amp;allocator=allocator_type())'],['../classsul_1_1dynamic__bitset.html#ade4a38b7afd0a1a61be651b7f1e6fa91',1,'sul::dynamic_bitset::dynamic_bitset(std::basic_string_view&lt; _CharT, _Traits &gt; str, typename std::basic_string_view&lt; _CharT, _Traits &gt;::size_type pos=0, typename std::basic_string_view&lt; _CharT, _Traits &gt;::size_type n=std::basic_string_view&lt; _CharT, _Traits &gt;::npos, _CharT zero=_CharT(&apos;0&apos;), _CharT one=_CharT(&apos;1&apos;), const allocator_type &amp;allocator=allocator_type())'],['../classsul_1_1dynamic__bitset.html#a72979987d5f4c4cfbf4c9528905f414c',1,'sul::dynamic_bitset::dynamic_bitset(const std::basic_string&lt; _CharT, _Traits, _Alloc &gt; &amp;str, typename std::basic_string&lt; _CharT, _Traits, _Alloc &gt;::size_type pos=0, typename std::basic_string&lt; _CharT, _Traits, _Alloc &gt;::size_type n=std::basic_string&lt; _CharT, _Traits, _Alloc &gt;::npos, _CharT zero=_CharT(&apos;0&apos;), _CharT one=_CharT(&apos;1&apos;), const allocator_type &amp;allocator=allocator_type())'],['../classsul_1_1dynamic__bitset.html#a48f7cc8cc4daf3485b4f305e3e473dc6',1,'sul::dynamic_bitset::dynamic_bitset(const _CharT *str, typename std::basic_string&lt; _CharT &gt;::size_type pos=0, typename std::basic_string&lt; _CharT &gt;::size_type n=std::basic_string&lt; _CharT &gt;::npos, _CharT zero=_CharT(&apos;0&apos;), _CharT one=_CharT(&apos;1&apos;), const allocator_type &amp;allocator=allocator_type())'],['../index.html',1,'dynamic_bitset']]],
  ['dynamic_5fbitset_2ehpp_6',['dynamic_bitset.hpp',['../dynamic__bitset_8hpp.html',1,'']]]
];
